"""create portfolio images

Revision ID: 04eb5c55a370
Revises: 0e6486dca8e9
Create Date: 2026-07-30 18:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04eb5c55a370'
down_revision: Union[str, None] = '0e6486dca8e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portfolio_images',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('braider_id', sa.UUID(), nullable=False),
        sa.Column('object_key', sa.String(length=500), nullable=False),
        sa.Column('caption', sa.String(length=300), nullable=True),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['braider_id'], ['braider_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('braider_id', 'position', name='uq_portfolio_image_position'),
    )
    op.create_index(
        op.f('ix_portfolio_images_braider_id'), 'portfolio_images', ['braider_id'], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_images_braider_id'), table_name='portfolio_images')
    op.drop_table('portfolio_images')
    # ### end Alembic commands ###
