"""add reviews and braider rating aggregates

Revision ID: 1b7e118b0927
Revises: 8d4a1f2e6c93
Create Date: 2026-08-08 16:09:13.870685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b7e118b0927'
down_revision: Union[str, None] = '8d4a1f2e6c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('braider_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment_en', sa.Text(), nullable=True),
    sa.Column('comment_de', sa.Text(), nullable=True),
    sa.Column('comment_fr', sa.Text(), nullable=True),
    sa.Column('comment_en_source', sa.Enum('HUMAN', 'MACHINE', 'PENDING', 'FAILED', name='bio_source'), nullable=True),
    sa.Column('comment_de_source', sa.Enum('HUMAN', 'MACHINE', 'PENDING', 'FAILED', name='bio_source'), nullable=True),
    sa.Column('comment_fr_source', sa.Enum('HUMAN', 'MACHINE', 'PENDING', 'FAILED', name='bio_source'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_reviews_rating_range'),
    sa.ForeignKeyConstraint(['braider_id'], ['braider_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'braider_id', name='uq_reviews_customer_braider')
    )
    op.create_index(op.f('ix_reviews_braider_id'), 'reviews', ['braider_id'], unique=False)
    op.create_index(op.f('ix_reviews_customer_id'), 'reviews', ['customer_id'], unique=False)
    op.add_column('braider_profiles', sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    # Existing rows have no value yet - a server-side default backfills them so
    # the NOT NULL constraint below doesn't reject the ALTER, then the default
    # is dropped since the ORM model applies default=0 on new inserts instead.
    op.add_column(
        'braider_profiles',
        sa.Column('rating_count', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('braider_profiles', 'rating_count', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('braider_profiles', 'rating_count')
    op.drop_column('braider_profiles', 'average_rating')
    op.drop_index(op.f('ix_reviews_customer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_braider_id'), table_name='reviews')
    op.drop_table('reviews')
    # ### end Alembic commands ###
    sa.Enum(name='review_status').drop(op.get_bind(), checkfirst=True)
