"""create braider service locations

Revision ID: 52664d03b80a
Revises: 05c9b777cd38
Create Date: 2026-07-30 20:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52664d03b80a'
down_revision: Union[str, None] = '05c9b777cd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'braider_service_locations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('braider_id', sa.UUID(), nullable=False),
        sa.Column('location_type', sa.Enum('HOME_STUDIO', 'SALON', name='location_type'), nullable=True),
        sa.Column('salon_name', sa.String(length=150), nullable=True),
        sa.Column('address_line1', sa.String(length=255), nullable=True),
        sa.Column('address_line2', sa.String(length=255), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('country', sa.String(length=2), nullable=True),
        sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column('offers_mobile', sa.Boolean(), nullable=False),
        sa.Column('travel_radius_km', sa.Integer(), nullable=True),
        sa.Column('travel_fee', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['braider_id'], ['braider_profiles.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(
        op.f('ix_braider_service_locations_braider_id'),
        'braider_service_locations',
        ['braider_id'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f('ix_braider_service_locations_braider_id'), table_name='braider_service_locations'
    )
    op.drop_table('braider_service_locations')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the Postgres enum type, which would break a
    # subsequent upgrade (CREATE TYPE collides with the leftover type).
    sa.Enum(name='location_type').drop(op.get_bind(), checkfirst=True)
