"""Add country to BookingCalculation

Revision ID: 61433c7c8373
Revises: ea860d9ca182
Create Date: 2026-08-04 22:55:42.632429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61433c7c8373'
down_revision: Union[str, None] = 'ea860d9ca182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_calculations', sa.Column('country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_calculations', 'country')
    # ### end Alembic commands ###
