"""add client location to booking calculation

Revision ID: b1d517665d34
Revises: 4204677c4476
Create Date: 2026-08-04 22:25:29.737998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1d517665d34'
down_revision: Union[str, None] = '4204677c4476'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_calculations', sa.Column('client_address', sa.String(length=500), nullable=True))
    op.add_column('booking_calculations', sa.Column('client_latitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('booking_calculations', sa.Column('client_longitude', sa.Numeric(precision=9, scale=6), nullable=True))
    op.drop_index('ix_booking_calculations_cleanup', table_name='booking_calculations', postgresql_where="(status = 'DRAFT'::booking_calculation_status)")
    op.drop_index('ix_braider_service_locations_earth', table_name='braider_service_locations', postgresql_using='gist', postgresql_where='((latitude IS NOT NULL) AND (longitude IS NOT NULL))')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_braider_service_locations_earth', 'braider_service_locations', [sa.text('ll_to_earth(latitude::double precision, longitude::double precision)')], unique=False, postgresql_using='gist', postgresql_where='((latitude IS NOT NULL) AND (longitude IS NOT NULL))')
    op.create_index('ix_booking_calculations_cleanup', 'booking_calculations', ['expires_at'], unique=False, postgresql_where="(status = 'DRAFT'::booking_calculation_status)")
    op.drop_column('booking_calculations', 'client_longitude')
    op.drop_column('booking_calculations', 'client_latitude')
    op.drop_column('booking_calculations', 'client_address')
    # ### end Alembic commands ###
