"""create braider profiles and onboarding statuses

Revision ID: b54001ef4885
Revises: af251b2be6d4
Create Date: 2026-07-30 13:06:51.244506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b54001ef4885'
down_revision: Union[str, None] = 'af251b2be6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('braider_onboarding_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Enum('BUSINESS_INFO', 'VERIFF', 'SERVICE_TYPE', 'PORTFOLIO', 'SERVICE_LOCATION', 'AVAILABILITY', 'PAYMENT_SETUP', 'COMPLETED', name='onboarding_step'), nullable=False),
    sa.Column('business_info_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('veriff_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_type_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('portfolio_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_location_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('availability_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_setup_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_braider_onboarding_statuses_user_id'), 'braider_onboarding_statuses', ['user_id'], unique=True)
    op.create_table('braider_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=150), nullable=True),
    sa.Column('logo_object_key', sa.String(length=500), nullable=True),
    sa.Column('bio_en', sa.Text(), nullable=True),
    sa.Column('bio_de', sa.Text(), nullable=True),
    sa.Column('bio_fr', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_braider_profiles_user_id'), 'braider_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_braider_profiles_user_id'), table_name='braider_profiles')
    op.drop_table('braider_profiles')
    op.drop_index(op.f('ix_braider_onboarding_statuses_user_id'), table_name='braider_onboarding_statuses')
    op.drop_table('braider_onboarding_statuses')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the Postgres enum types created for these
    # tables' Enum columns, which leaves them orphaned and breaks a
    # subsequent upgrade (CREATE TYPE collides with the leftover type).
    sa.Enum(name='gender').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='onboarding_step').drop(op.get_bind(), checkfirst=True)
