"""Add booking models

Revision ID: b9b03605242c
Revises: 61433c7c8373
Create Date: 2026-08-04 23:32:19.430983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9b03605242c'
down_revision: Union[str, None] = '61433c7c8373'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_webhook_events',
    sa.Column('stripe_event_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('stripe_event_id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('braider_id', sa.UUID(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING_PAYMENT', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'NO_SHOW', 'CANCELLED_BY_CUSTOMER', 'CANCELLED_BY_BRAIDER', 'CANCELLED_NO_PAYMENT', 'EXPIRED', 'DISPUTED', name='bookingstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('braider_timezone', sa.String(length=50), nullable=False),
    sa.Column('client_address', sa.String(length=500), nullable=True),
    sa.Column('client_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('client_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_on_service', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_on_platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('braider_share_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('braider_share_deposit', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('braider_share_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee_type', postgresql.ENUM('PERCENTAGE', 'FIXED', name='settingvaluetype'), nullable=False),
    sa.Column('platform_fee_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_service_type', postgresql.ENUM('PERCENTAGE', 'FIXED', name='settingvaluetype'), nullable=False),
    sa.Column('vat_service_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_platform_fee_type', postgresql.ENUM('PERCENTAGE', 'FIXED', name='settingvaluetype'), nullable=False),
    sa.Column('vat_platform_fee_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_type', postgresql.ENUM('PERCENTAGE', 'FIXED', name='settingvaluetype'), nullable=False),
    sa.Column('deposit_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('braider_vat_status', sa.String(length=50), nullable=True),
    sa.Column('braider_vat_number', sa.String(length=50), nullable=True),
    sa.Column('payment_schedule', postgresql.ENUM('FULL_UPFRONT', 'DEPOSIT_THEN_BALANCE', name='paymentschedule'), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance_charge_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_charge_state', postgresql.ENUM('SCHEDULED', 'ABANDONED', name='balancechargestate'), nullable=True),
    sa.Column('balance_charge_attempts', sa.Integer(), nullable=False),
    sa.Column('balance_charge_last_error', sa.Text(), nullable=True),
    sa.Column('appointment_reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('balance_reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_card_exp_month', sa.Integer(), nullable=True),
    sa.Column('stripe_card_exp_year', sa.Integer(), nullable=True),
    sa.Column('terms_version', sa.String(length=20), nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.CheckConstraint('braider_share_deposit + braider_share_balance = braider_share_total', name='ck_bookings_pricing_braider_shares'),
    sa.CheckConstraint('subtotal + platform_fee + vat_total = total', name='ck_bookings_pricing_total'),
    sa.CheckConstraint('vat_on_service + vat_on_platform_fee = vat_total', name='ck_bookings_pricing_vat_total'),
    sa.ForeignKeyConstraint(['braider_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_table('booking_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('item_type', postgresql.ENUM('SERVICE', 'VARIATION', 'ADDON', 'TRAVEL', 'PLATFORM_FEE', 'VAT_SERVICE', 'VAT_PLATFORM_FEE', name='bookingitemtype'), nullable=False),
    sa.Column('source_style_id', sa.UUID(), nullable=True),
    sa.Column('source_style_variation_id', sa.UUID(), nullable=True),
    sa.Column('source_addon_id', sa.UUID(), nullable=True),
    sa.Column('source_braider_style_addon_id', sa.UUID(), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('name_fr', sa.String(length=255), nullable=True),
    sa.Column('line_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('purpose', postgresql.ENUM('FULL', 'DEPOSIT', 'BALANCE', name='paymentpurpose'), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', 'ABANDONED', name='paymentstatus'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('braider_share_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_refunded_minor', sa.BigInteger(), nullable=False),
    sa.Column('amount_transferred_minor', sa.BigInteger(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('is_off_session', sa.Boolean(), nullable=False),
    sa.Column('transfer_group', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_booking_payment_succeeded', 'booking_payments', ['booking_id', 'purpose'], unique=True, postgresql_where="(status = 'SUCCEEDED')")
    op.create_foreign_key(None, 'booking_calculations', 'bookings', ['consumed_by_booking_id'], ['id'], ondelete='SET NULL')
    
    # Custom exclusion constraint for double-booking prevention
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("""
        ALTER TABLE bookings ADD CONSTRAINT ex_bookings_no_overlap
        EXCLUDE USING gist (braider_id WITH =, tstzrange(blocked_from, blocked_until, '[)') WITH &&)
        WHERE (status IN ('PENDING_PAYMENT','CONFIRMED','IN_PROGRESS','COMPLETED','NO_SHOW','DISPUTED'))
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking_calculations', type_='foreignkey')
    op.drop_index('uq_booking_payment_succeeded', table_name='booking_payments', postgresql_where="(status = 'SUCCEEDED')")
    op.drop_table('booking_payments')
    op.drop_table('booking_items')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('stripe_webhook_events')
    op.execute("ALTER TABLE bookings DROP CONSTRAINT IF EXISTS ex_bookings_no_overlap")
    # ### end Alembic commands ###
