"""add bio translation source tracking

Revision ID: e2c526692fbc
Revises: b54001ef4885
Create Date: 2026-07-30 13:25:07.028362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2c526692fbc'
down_revision: Union[str, None] = 'b54001ef4885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike create_table, a standalone ADD COLUMN doesn't implicitly create
    # the enum type, so it's created explicitly once before the 3 columns
    # that share it (see downgrade() for the matching drop).
    bio_source_enum = sa.Enum('HUMAN', 'MACHINE', 'PENDING', 'FAILED', name='bio_source')
    bio_source_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('braider_profiles', sa.Column('bio_en_source', bio_source_enum, nullable=True))
    op.add_column('braider_profiles', sa.Column('bio_de_source', bio_source_enum, nullable=True))
    op.add_column('braider_profiles', sa.Column('bio_fr_source', bio_source_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('braider_profiles', 'bio_fr_source')
    op.drop_column('braider_profiles', 'bio_de_source')
    op.drop_column('braider_profiles', 'bio_en_source')
    # ### end Alembic commands ###
    # Autogenerate doesn't drop the Postgres enum type shared by these three
    # columns, which would break a subsequent upgrade (see b54001ef4885).
    sa.Enum(name='bio_source').drop(op.get_bind(), checkfirst=True)
