"""Add CountryVatSettings

Revision ID: ea860d9ca182
Revises: b1d517665d34
Create Date: 2026-08-04 22:48:51.779787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from datetime import UTC, datetime


# revision identifiers, used by Alembic.
revision: str = 'ea860d9ca182'
down_revision: Union[str, None] = 'b1d517665d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects import postgresql
    
    setting_value_type = postgresql.ENUM('PERCENTAGE', 'FIXED', name='setting_value_type', create_type=False)
    
    op.create_table('country_vat_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('vat_type', setting_value_type, nullable=False),
    sa.Column('vat_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_platform_fee_type', setting_value_type, nullable=False),
    sa.Column('vat_platform_fee_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("vat_value >= 0 AND vat_platform_fee_value >= 0 AND (vat_type != 'PERCENTAGE' OR vat_value <= 100) AND (vat_platform_fee_type != 'PERCENTAGE' OR vat_platform_fee_value <= 100)", name='ck_country_vat_settings_value_ranges'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_vat_settings_country'), 'country_vat_settings', ['country'], unique=True)
    
    country_vat_table = sa.table(
        'country_vat_settings',
        sa.column('id', sa.UUID),
        sa.column('country', sa.String),
        sa.column('vat_type', setting_value_type),
        sa.column('vat_value', sa.Numeric),
        sa.column('vat_platform_fee_type', setting_value_type),
        sa.column('vat_platform_fee_value', sa.Numeric),
        sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('updated_at', sa.DateTime(timezone=True))
    )
    
    op.bulk_insert(country_vat_table, [
        {
            'id': uuid.uuid4(),
            'country': 'DE',
            'vat_type': 'PERCENTAGE',
            'vat_value': 19.00,
            'vat_platform_fee_type': 'PERCENTAGE',
            'vat_platform_fee_value': 19.00,
            'created_at': datetime.now(UTC),
            'updated_at': datetime.now(UTC)
        },
        {
            'id': uuid.uuid4(),
            'country': 'FR',
            'vat_type': 'PERCENTAGE',
            'vat_value': 20.00,
            'vat_platform_fee_type': 'PERCENTAGE',
            'vat_platform_fee_value': 20.00,
            'created_at': datetime.now(UTC),
            'updated_at': datetime.now(UTC)
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_vat_settings_country'), table_name='country_vat_settings')
    op.drop_table('country_vat_settings')
    # ### end Alembic commands ###
