"""add remember_me flag to refresh tokens

Revision ID: f64ebd1bde7b
Revises: e2c526692fbc
Create Date: 2026-07-30 14:44:10.795632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64ebd1bde7b'
down_revision: Union[str, None] = 'e2c526692fbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; NOT NULL would otherwise fail
    # against a non-empty refresh_tokens table.
    op.add_column(
        'refresh_tokens',
        sa.Column('remember_me', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'remember_me')
    # ### end Alembic commands ###
