"""create veriff sessions

Revision ID: fc684c8459b8
Revises: f64ebd1bde7b
Create Date: 2026-07-30 15:04:11.214929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc684c8459b8'
down_revision: Union[str, None] = 'f64ebd1bde7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veriff_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('veriff_session_id', sa.String(length=64), nullable=False),
    sa.Column('verification_url', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'SUBMITTED', 'APPROVED', 'DECLINED', 'RESUBMISSION_REQUESTED', 'REVIEW', 'EXPIRED', 'ABANDONED', name='veriff_session_status'), nullable=False),
    sa.Column('decision_code', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('reason_code', sa.Integer(), nullable=True),
    sa.Column('acceptance_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submission_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_webhook_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veriff_sessions_user_id'), 'veriff_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_veriff_sessions_veriff_session_id'), 'veriff_sessions', ['veriff_session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veriff_sessions_veriff_session_id'), table_name='veriff_sessions')
    op.drop_index(op.f('ix_veriff_sessions_user_id'), table_name='veriff_sessions')
    op.drop_table('veriff_sessions')
    # ### end Alembic commands ###
    # create_table implicitly creates the enum type, but drop_table does NOT
    # drop it - same gotcha hit in b54001ef4885 and e2c526692fbc. Without
    # this, a subsequent upgrade fails with "type already exists".
    sa.Enum(name='veriff_session_status').drop(op.get_bind(), checkfirst=True)
